In [1]:
import numpy as np

In [4]:
#1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
m = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]], dtype=int)

print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
#3.  Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
rows, cols = 5, 5

array = np.random.randint(1, 11, size=(rows, cols))

print(array)

[[10  4  6 10  3]
 [ 4  2  8 10 10]
 [ 6  1  3  1  1]
 [ 8  2  8  5  4]
 [ 2  6  3  6  1]]


In [11]:
#4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


rows, cols = 4, 4
min, max = 0, 1.0

array = np.random.uniform(min, max, size=(rows, cols))

print(array)

[[0.97977943 0.91525142 0.37175133 0.73783477]
 [0.10721991 0.65375397 0.56945884 0.00928965]
 [0.52070995 0.76541706 0.10061202 0.56557534]
 [0.81063865 0.1927011  0.95994562 0.8323706 ]]


In [14]:
#5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
sum = a + b
diff = a - b
product = a*b

print(sum)
print(diff)
print(product)

[ 6  1 10 10  3] [ 9  6  3  4 10]
[15  7 13 14 13]
[-3 -5  7  6 -7]
[54  6 30 40 30]


In [15]:
#6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a = np.random.rand(7)
b = np.random.rand(7)

scalar = np.dot(a,b)
print(scalar)

1.1282955757586397


In [18]:
#7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
m1 = np.random.randint(1, 11, size =(2,2))
m2 = np.random.randint(1, 11, size= (2,3))

product = np.dot(m1, m2)
print(product)

[[ 6  9 17]
 [ 6  9 17]]


In [19]:
#8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
m = np.random.randint(1, 11, size =(3, 3))
print(m)

m_inv = np.linalg.inv(m)
print(m_inv)


[[10  9  3]
 [ 9  2  3]
 [ 2  8 10]]
[[ 0.00675676  0.11148649 -0.03547297]
 [ 0.14189189 -0.15878378  0.00506757]
 [-0.11486486  0.10472973  0.10304054]]


In [21]:
#9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

m = np.random.uniform(0, 1.0, size=(4,4))
b = m.T

print(b)

[[0.40521519 0.40128254 0.5121778  0.21191053]
 [0.59700926 0.60199624 0.43546298 0.03888895]
 [0.96552962 0.14489279 0.70181658 0.86387195]
 [0.94963052 0.0085561  0.99675405 0.31697613]]
[[0.40521519 0.59700926 0.96552962 0.94963052]
 [0.40128254 0.60199624 0.14489279 0.0085561 ]
 [0.5121778  0.43546298 0.70181658 0.99675405]
 [0.21191053 0.03888895 0.86387195 0.31697613]]


In [7]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
m1 = np.random.randint(1, 11, size =(3,4))
a = np.random.randint(1, 11, size=4)

product = np.dot(m1, a)
print(product)

[ 66 112 157]


In [9]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
m = np.random.uniform(0, 1.0, size=(2,3))
a = np.random.uniform(1, 11, size=3)

product = np.dot(m, a)
print(product)

[ 3.68606289 10.80738456]


In [11]:
#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
m1 = np.random.randint(1, 11, size =(2,2))
m2 = np.random.randint(1, 11, size= (2,2))

print(m1*m2)


[[63 48]
 [30 42]]


In [14]:
#13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
m1 = np.random.randint(1, 11, size =(2,2))
m2 = np.random.randint(1, 11, size= (2,2))

product = np.dot(m1,m2)
print(product)

[[32 30]
 [65 50]]


In [20]:
#14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
m1 = np.random.randint(1, 101, size =(5,5))
print(m1.sum())

1237


In [23]:
#15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
m1 = np.random.randint(1, 11, size =(4,4))
m2 = np.random.randint(1, 11, size =(4,4))

print(m1-m2)

[[-3 -6 -3  4]
 [-4  0  5  0]
 [ 3 -2 -2  0]
 [ 0  0  1  5]]


In [35]:
#16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
m = np.random.uniform(0, 1.0, size=(3, 3))

vector = np.sum(m, axis=1, keepdims=True)
print(vector)

[[0.78972506]
 [1.69484458]
 [1.7906857 ]]


In [36]:
#17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
m = np.random.randint(1, 11, size =(3,4))
print(m)

square_m = m**2

print(square_m)

[[ 6 10 10  6]
 [ 2  6  5  3]
 [ 4  7  2  2]]
[[ 36 100 100  36]
 [  4  36  25   9]
 [ 16  49   4   4]]


In [42]:
#18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
a = np.random.randint(1, 51, size =4)
print(a)

a_kor = np.sqrt(a)
print(a_kor)

[ 4 40  7 48]
[2.         6.32455532 2.64575131 6.92820323]
